name: tasks
description: A to do app to track and remind you of your tasks. 
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  # State Management
  stacked: ^2.3.0
  stacked_services: ^0.8.22
  intl: ^0.17.0
  uuid: ^3.0.6
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  flutter_svg: ^1.0.3
  awesome_notifications: ^0.6.21
  flutter_chips_input: ^1.10.0
  animations: ^2.0.2
dev_dependencies:
  hive_generator: ^1.1.2
  build_runner: ^2.1.10
  stacked_generator: ^0.6.2
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

 
  assets:
    - assets/empty_state.svg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
